### ISSUE TITLE
HTML-Conversion unsupported: Operation cannot be performed on the specified input media type : text/html

### ISSUE THREAD

**Issue by jankammerath** [adobe/pdftools-node-sdk-samples#15]
```
Error: Operation cannot be performed on the specified input media type : text/html
at validateAllowedMediaType (/var/task/node_modules/@adobe/documentservices-pdftools-node-sdk/src/internal/util/validation-util.js:86:9)
at CreatePDFOperation.validate (/var/task/node_modules/@adobe/documentservices-pdftools-node-sdk/src/operation/create-pdf-operation.js:414:3)
at CreatePDFOperation.execute (/var/task/node_modules/@adobe/documentservices-pdftools-node-sdk/src/operation/create-pdf-operation.js:397:9)

```
### Expected Behaviour
Convert html content to a PDF file

### Actual Behaviour
Throw an exception

### Reproduce Scenario (including but not limited to)
`PDFToolsSdk.FileRef.createFromStream(Readable.from([htmlContent]),'text/html')`

#### Steps to Reproduce
`PDFToolsSdk.FileRef.createFromStream(Readable.from([htmlContent]),'text/html')`

#### Platform and Version
Docker (Amazon Linux 2)

#### Sample Code that illustrates the problem
`PDFToolsSdk.FileRef.createFromStream(Readable.from([htmlContent]),'text/html')`

**Comment by jankammerath** [comment]
Got it resolved. The HTML content needed to be zipped as "index.html" and then pushed in with "application/zip".
